# Richard Sprague
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Richard Sprague
email: richardsprague+homepage@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Years building software marketing and engineering teams at Apple, Microsoft
  and startups in Japan, China, and the U.S.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://richardsprague.com" # the base hostname & protocol for your site
twitter_username: sprague
github_username:  richardsprague

highlighter: rouge
plugins:
  - jekyll-paginate
  
# Build settings
markdown: kramdown

